#============================#
# Project 配置
#============================#
# 环境
prefile: dev

#============================#
# server 配置
#============================#
server:
  # 端口
  port: 8001

#============================#
# file 配置
#============================#
file:
  # 文件上传目录
  upload-folder: D://javadog/chat
